// <auto-generated />
namespace StarwarsUniverse.Console.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adjustments1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adjustments1));
        
        string IMigrationMetadata.Id
        {
            get { return "201602091449461_adjustments1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
